export const LOAD_USER_SUCCESS="LOAD_USER_SUCCES";
export const LOAD_USER_FAIL="LOAD_USER_FAIL";
export const REGISTER_SUCCESS="REGISTER_SUCCES";
export const REGISTER_FAIL="REGISTER_FAIL";
export const LOGIN_SUCCESS="LOGIN_SUCCES";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOADING="LOADING";
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
