export const GET_MOVIE_SUCCES="GET_MOVIE_SUCCES";
export const GET_MOVIE_FAIL="GET_MOVIE_FAIL";
export const UPDATE_MOVIE_SUCCES="UPDATE_MOVIE_SUCCES";
export const UPDATE_MOVIE_FAIL="UPDATE_MOVIE_FAIL";
export const DELETE_MOVIE_SUCCESS="DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_FAIL="DELETE_MOVIE_FAIL";
export const GET_ALL_MOVIES_SUCCESS="GET_ALL_MOVIES_SUCCESS";
export const GET_ALL_MOVIES_FAIL="GET_ALL_MOVIES_FAIL";
export const GET_RANDUM_MOVIES_SUCCESS="GET_RANDUM_MOVIES_SUCCESS";
export const GET_RANDUM_MOVIES_FAIL="GET_RANDUM_MOVIES_FAIL";

export const LOADING_ALL="LOADING_ALL"
export const LOADING_MOVIE="LOADING_MOVIE"
export const LOADING_RANDUM="LOADING_RANDUM"

export const CREATE_MOVIE_SUCCES="CREATE_MOVIE_SUCCES"
export const CREATE_MOVIE_FAIL="CREATE_MOVIE_FAIL"
export const STATS_MOVIE_SUCCES="STATS_MOVIE_SUCCES"
export const STATS_MOVIE_FAIL="STATS_MOVIE_FAIL"